name       : scummvm
version    : 2.7.0
release    : 23
source     :
    - https://github.com/scummvm/scummvm/archive/refs/tags/v2.7.0.tar.gz : c2a1fda1f5e2602294fda4a9cb502e3912ca74d09c6519e82ee09995c3f1d801
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
    - GPL-3.0-or-later WITH Font-exception-2.0
    - ISC
    - LGPL-2.1-or-later
    - MIT
    - OFL-1.1
component  : games.emulator
summary    : ScummVM is a program which allows you to run certain classic graphical point-and-click adventure games, provided you already have their data files
description: |
    ScummVM is a program which allows you to run certain classic graphical point-and-click adventure games, provided you already have their data files. The clever part about this: ScummVM just replaces the executables shipped with the games, allowing you to play them on systems for which they were never designed!
builddeps  :
    - pkgconfig(SDL2_net)
    - pkgconfig(alsa)
    - pkgconfig(faad2)
    - pkgconfig(flac)
    - pkgconfig(fluidsynth)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libmpeg2)
    - pkgconfig(libturbojpeg)
    - pkgconfig(mad)
    - pkgconfig(theoradec)
    - pkgconfig(vorbisfile)
    - giflib-devel
    - liba52dec-devel
setup      : |
    %configure \
        --datadir=/usr/share/scummvm \
        --disable-debug \
        --enable-release
build      : |
    %make
install    : |
    %make_install
    rm -fr $installdir/usr/share/doc
check      : |
    %make test
