name       : scummvm
version    : 2.0.0
release    : 5
source     :
    - https://www.scummvm.org/frs/scummvm/2.0.0/scummvm-2.0.0.tar.xz : 9784418d555ba75822d229514a05cf226b8ce1a751eec425432e6b7e128fca60
license    : GPL-2.0
component  : games.emulator
summary    : ScummVM is a program which allows you to run certain classic graphical point-and-click adventure games, provided you already have their data files.
description: |
    ScummVM is a program which allows you to run certain classic graphical point-and-click adventure games, provided you already have their data files. The clever part about this: ScummVM just replaces the executables shipped with the games, allowing you to play them on systems for which they were never designed!
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(flac)
    - pkgconfig(fluidsynth)
    - pkgconfig(libjpeg)
    - pkgconfig(libmpeg2)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(sdl2)
    - pkgconfig(theoradec)
    - pkgconfig(vorbisfile)
    - pkgconfig(x11)
    - faad-devel
    - libmad-devel
setup      : |
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 dists/scummvm.desktop $installdir/usr/share/applications/scummvm.desktop
