name       : scummvm
version    : 2.0.0
release    : 11
source     :
    - https://github.com/scummvm/scummvm/archive/v2.0.0.tar.gz : 1a7cb080d956220657734ac42f75168552171bd13983d58c4bd07fdf31bcc59a
license    : GPL-2.0-only
component  : games.emulator
summary    : ScummVM is a program which allows you to run certain classic graphical
    point-and-click adventure games, provided you already have their data files
description: |
    ScummVM is a program which allows you to run certain classic graphical point-and-click adventure games, provided you already have their data files. The clever part about this: ScummVM just replaces the executables shipped with the games, allowing you to play them on systems for which they were never designed!
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(flac)
    - pkgconfig(fluidsynth)
    - pkgconfig(libmpeg2)
    - pkgconfig(libopenjp2)
    - pkgconfig(libturbojpeg)
    - pkgconfig(sdl2)
    - pkgconfig(theoradec)
    - pkgconfig(vorbisfile)
    - pkgconfig(x11)
    - faad-devel
    - libmad-devel
setup      : |
    %patch -p1 < $pkgfiles/security/CVE-2017-17528.patch
    %patch -p1 < $pkgfiles/Do-not-hang-ScummVM-when-opening-a-browser.patch
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 dists/scummvm.desktop $installdir/usr/share/applications/scummvm.desktop
check      : |
    %make test
