name       : scummvm
version    : 2.5.0
release    : 18
source     :
    - https://github.com/scummvm/scummvm/archive/refs/tags/v2.5.0.tar.gz : 3a6cd395e87232046a5ff05634f4cd872c540dbd80423577c0c56cb8218769c8
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - GPL-3.0-or-later WITH Font-exception-2.0
    - LGPL-2.1-or-later
    - OFL-1.1
component  : games.emulator
summary    : ScummVM is a program which allows you to run certain classic graphical point-and-click adventure games, provided you already have their data files
description: |
    ScummVM is a program which allows you to run certain classic graphical point-and-click adventure games, provided you already have their data files. The clever part about this: ScummVM just replaces the executables shipped with the games, allowing you to play them on systems for which they were never designed!
builddeps  :
    - pkgconfig(SDL2_net)
    - pkgconfig(alsa)
    - pkgconfig(faad2)
    - pkgconfig(flac)
    - pkgconfig(fluidsynth)
    - pkgconfig(glew)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libmpeg2)
    - pkgconfig(libturbojpeg)
    - pkgconfig(mad)
    - pkgconfig(theoradec)
    - pkgconfig(vorbisfile)
    - giflib-devel
    - liba52dec-devel
setup      : |
    ./configure \
        --enable-c++11 \
        --enable-release \
        --disable-debug \
        --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    rm -fr $installdir/usr/share/doc
check      : |
    %make test
